### ISSUE TITLE
queue01.c 파일에서 마지막에 출력을 입력받는 배열문제

### ISSUE THREAD

**Issue by kokodakdak** [kokodakdak/Data-Struct#2]
배열에 입력한 숫자가 아닌 쓰레기 값이 들어가서 남아있는듯?

**Comment by baesy0** [comment]
국어 실력이 안 좋으시군여. 알아듣게 찬찬히 설명해주세여ㅋㅋㅋㅋ

**Comment by kokodakdak** [comment]
printf("%d",&변수)이런식으로 해서 주소값이 들어간거였습니다. 
수정할께여 ㅎ

**Comment by baesy0** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이런걸로 이슈올리지 마시져^^
