### ISSUE TITLE
queue01.c main문에 이

### ISSUE THREAD

**Issue by kokodakdak** [kokodakdak/Data-Struct#3]
size를 count 라는 변수에다가 저장을 하는데 push와 pop을 할떄마다 더하고 빼고 하는 식으로 사용하고 있습니다. 하지만 정작 size를 배열에 넣을때는 0으로 입력됨

**Comment by jeongsunyong** [comment]
strcmp에 printf에 테스트를 넣을 시 진입이 안됩니다
push에 진입이 안됬으므로 count도 증가하지 않는것입니다~
문제 조건이 push ***로 입력값이 주어지므로
strncmp (str,"push",4) 4번째까지 문자열 비교
하는 함수를 쓰던가 해야되욤

**Comment by kokodakdak** [comment]
Push는 되는데 count만 안된다는 건가여?

**Comment by jeongsunyong** [comment]
아니네요
count는 늘어나는데

for (i = 0; i < num; i++)
	{
		scanf("%s", &str);

		printf("%s\n", str);
		if (strcmp(str,"push") == 0)
		{
			scanf("%d", &data);
			enQueue(LQ, data);
			count++;

		}
이렇게 테스트를 해봤는데

push 15를 입력했을 때 str에는 push만 남아있었어서
queue에 데이터 입력이 안되요

입력창에서 push 15이런식으로 입력이 되는데 
push 만 입력이 되고 뒤에 숫자는 날아가버려요 
scanf가 띄어쓰기를 공백으로 인식해서 뒤에가 사라져요
